### ISSUE TITLE
出现No package 'xkbfile' found一gyp ERR! configure error 异常,且运行wechat-devtools后源代码窗口为空

### ISSUE THREAD

**Issue by Wanxp** [dragonation/wechat-devtools#32]
### 环境:
[] ubuntu20.4.01
[] wine5.0-ubuntu
### 异常描述
执行命令
```
./tools/setup-wechat-devtools
```
后前面正常,后面输出结果出现异常.异常内容如下.打开wechat-devtools后源代码无法查看,窗口显示空白

```
> native-keymap@2.2.1 install /home/wanxp/program/wechat-devtools/package.nw/node_modules_tmp/node_modules/native-keymap
> node-gyp rebuild

Package xkbfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbfile' found
gyp: Call to '${PKG_CONFIG:-pkg-config} x11 xkbfile --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/wanxp/program/wechat-devtools/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.0-59-generic
gyp ERR! command "/home/wanxp/program/wechat-devtools/node/bin/node" "/home/wanxp/program/wechat-devtools/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wanxp/program/wechat-devtools/package.nw/node_modules_tmp/node_modules/native-keymap
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/wanxp/program/wechat-devtools/package.nw/node_modules_tmp/package.json'
npm WARN node_modules_tmp No description
npm WARN node_modules_tmp No repository field.
npm WARN node_modules_tmp No README data
npm WARN node_modules_tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-keymap@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-keymap@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wanxp/.npm/_logs/2020-12-20T09_10_48_397Z-debug.log
cp: cannot stat '/home/wanxp/program/wechat-devtools/tools/../package.nw/node_modules_tmp/node_modules/vscode-ripgrep/bin/rg': No such file or directory
12-20 17:10:48.725   [INFO] Patching wechat-devtools (wechat-devtools/tools/update-wechat-devtools:173)
12-20 17:10:49.248   [INFO] Patching wcc and wcsc (wechat-devtools/tools/update-wechat-devtools:179)
```
### 可能的解决方案
根据[no-package-xkbfile-found-when-build-vscode-on-ubuntu](https://stackoverflow.com/questions/55878536/no-package-xkbfile-found-when-build-vscode-on-ubuntu)描述类似的问题,给出的方案是:
```
sudo apt-get install -y g++ gcc make python2.7 pkg-config libx11-dev libxkbfile-dev
```
再重新执行
```
./tools/setup-wechat-devtools
```
即可

**Comment by tidjean** [comment]
try this:

sudo apt-get install -y g++ gcc make python2.7 pkg-config libx11-dev libxkbfile-dev

**Comment by Wanxp** [comment]
"
try this:
sudo apt-get install -y g++ gcc make python2.7 pkg-config libx11-dev libxkbfile-dev
"
it works,thanks
